### ISSUE TITLE
cleanup_metric_name does not handle integers for metric names

### ISSUE THREAD

**Issue by michaelkaye** [daniellawrence/graphitesend#74]
For instance, if you want to store and graph values for all your customers using their customer ID, you might write code like this:
```
sender.init(prefix='customers', postfix='.value')
for customer in customer:
    sender.send(customer.pkey, get_customer_value(customer))
```
This looks OK code wise, but since pkey is actually from a database and is represented as an int, you get an error:
```
graphitesend.py", line 217, in clean_metric_name
    metric_name = metric_name.replace('(', '_').replace(')', '')
AttributeError: 'int' object has no attribute 'replace'
```

I can (and have) stuck in a str() to do the right thing for now, but depending on what your opinion is on doing things to make users' code cleaner, perhaps handling this in the library would be a good idea?

**Comment by Shir0kamii** [comment]
Hi! I agree with you, it's best in this case to cast on our side. Since it's obvious that text is expected as a metric_name, one would think it's automatically converted if it's not.

I've made the change and merged it, but the authors seems to be busy lately, and he's the only one with release rights. You can still `pip` the fixed version using the commit as reference: `pip install -e git+https://github.com/daniellawrence/graphitesend.git@2a97907#egg=graphitesend`.

**Comment by michaelkaye** [comment]
Thanks for responding so quickly. The script is a one-off so I don't have a need to use it myself, but it's good it's there for the future.
